# Chapter 6 - Other Popular Machine Learning Methods
## Segment 2 - A neural network with a Perceptron

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
from sklearn.linear_model import Perceptron

In [3]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [6]:
standardized_X_train[0:10,]

array([[-0.2225873 , -0.12387991,  0.25630158,  0.17905916],
       [ 0.65522178, -0.7702099 ,  0.71620721,  0.83817262],
       [-0.3479886 , -1.41653988,  0.08383696, -0.08458623],
       [ 0.65522178, -1.20109656,  0.71620721,  0.44270454],
       [-0.2225873 , -0.7702099 ,  0.31378978,  0.17905916],
       [-1.47660028,  0.7378934 , -1.29587994, -1.13916776],
       [-0.3479886 , -1.41653988,  0.02634876, -0.21640892],
       [ 0.27901789, -0.12387991,  0.65871901,  0.83817262],
       [ 1.15682697,  0.09156341,  0.42876619,  0.31088185],
       [-1.35119898,  0.30700674, -1.18090353, -1.27099045]])

In [7]:
standardized_X_test[0:10,]

array([[ 0.6738558 ,  0.15152174,  0.29633776,  0.21398739],
       [-0.00757141, -0.19814381,  0.24007109,  0.08024527],
       [ 0.6738558 , -0.19814381,  0.57767107,  1.28392434],
       [-1.25685463,  1.55018394, -1.61672877, -1.39091804],
       [-1.48399703, -0.19814381, -1.56046211, -1.65840228],
       [-1.37042583,  0.15152174, -1.50419545, -1.52466016],
       [ 0.33314219, -0.89747491,  0.80273772,  1.15018223],
       [ 0.9009982 ,  0.15152174,  0.6902044 ,  1.01644011],
       [ 1.2417118 ,  0.50118729,  1.02780437,  0.61521375],
       [-1.25685463,  1.20051839, -1.44792879, -1.25717592]])

In [8]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.15,
           fit_intercept=True, max_iter=50, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=15, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [9]:
y_pred = perceptron.predict(standardized_X_test)

In [10]:
print(y_test)

[1 1 2 0 0 0 2 2 2 0 1 2 0 1 2 2 2 2 1 1 1 0 0 2 2 1 2 0 2 1]


In [11]:
print(y_pred)

[0 1 2 0 1 0 2 2 2 0 1 2 0 1 1 2 2 1 1 1 1 0 0 1 2 0 1 0 2 0]


In [12]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.70      0.88      0.78         8
           1       0.55      0.67      0.60         9
           2       1.00      0.69      0.82        13

    accuracy                           0.73        30
   macro avg       0.75      0.74      0.73        30
weighted avg       0.78      0.73      0.74        30

